### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by mars3142** [inapay/iban_form_field#9]
Can you make your package null safe? That would be fine.

**Comment by abel-123** [comment]
Yes, please!

**Comment by haarts** [comment]
Fixed in 0.2.3

**Comment by mars3142** [comment]
Please don't use ! for nullable fields, if you don't check for null in the first place. Your last commit is really bad. Please use ? and check the result for true/false, which is the correct solution instead of using ! in the if statement.

**Comment by haarts** [comment]
I'm looking forward to your pull request. :)
